apiVersion: apps/v1
kind: Deployment

metadata:
  name: dev-workspace
  namespace: dev

spec:
  replicas: 3

  selector:
    matchLabels:
      app: dev-workspace

  template:
    metadata:
      labels:
        app: dev-workspace

    spec:
      containers:
        - name: dev
          image: ghcr.io/k-kanke/dev-workspace:0.5

          command: ["sleep", "infinity"]

          ports:
            - containerPort: 3000

          volumeMounts:
            - name: workspace
              mountPath: /workspace

      volumes:
        - name: workspace
          persistentVolumeClaim:
            claimName: dev-workspace
