apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: tailscale-operator
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://pkgs.tailscale.com/helmcharts
    chart: tailscale-operator

    # Tailscaleのリリースと合わせて固定する
    targetRevision: 1.98.8

    helm:
      values: |
        operatorConfig:
          defaultTags:
            - tag:k8s-operator

  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
